import { Box, Stack } from "@chakra-ui/react";
import { Claim, useAllClaims } from "../claims/useAllClaims";

import Head from "next/head";
import { Layout } from "../components/layout";
import { Suspense } from "react";

function TestClaimBox(claim: Claim) {
  return (
    <Box border="1px" borderColor="black" w="200px" h="300px">
      {claim.id}
    </Box>
  );
}

function TestClaimsList() {
  const { data, isPending, error } = useAllClaims(3, 0);

  if (isPending) return "Loading...";

  if (error) return "An error has occurred: " + error.message;

  return (
    <Stack direction={["column", "row"]} spacing="24px">
      {data.claims.map((claim) => (
        <TestClaimBox key={claim.id} {...claim} />
      ))}
    </Stack>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TestClaimsList />
      </Layout>
    </>
  );
}
